import type { Metadata } from "next";
import { inter, sourceSerif, ibmPlexMono } from '@/fonts/font'
import "../globals.css";
import AppShell from "@/components/layout/AppShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${sourceSerif.variable} ${ibmPlexMono.variable}`}
    >
      <body>
        <AppShell>

                 {children}
        </AppShell>
      </body>
    </html>
  )
}
